eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.12.227:8090/eureka,http://172.16.12.234:8090/eureka,http://172.16.12.237:8090/eureka
spring:
  redis:
    host: r-wz95ncjqmifbmhywo1.redis.rds.aliyuncs.com
    port: 6379
    password: Iyouqu123
    database: 0
    jedis:
      pool:
        max-wait: 3s
        min-idle: 50
        max-idle: 1000
        max-active: 2000
    timeout: 5s