spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        pool:
          acquire-timeout: 6000
          max-connections: 10000
        connect-timeout: 10000
      discovery:
        locator:
          enabled: true
      routes:
#        - id: union3
#          uri: lb://UNION3
#          predicates:
#            - Path=/union3/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                #用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象
##                key-resolver: "#{@userKeyResolver}"
#                #令牌桶每秒填充平均速率
#                redis-rate-limiter.replenishRate: 1
#                #令牌桶总容量
#                redis-rate-limiter.burstCapacity: 1
      default-filters:
      # 熔断降级配置
        - name: Hystrix
          args:
            name : default
            fallbackUri: 'forward:/defaultfallback'
      # redis限流 ， filter名称必须是RequestRateLimiter
#        - name: RequestRateLimiter
#          args:
#            # 使用SpEL名称引用Bean，与上面新建的RateLimiterConfig类中的bean的name相同
#            key-resolver: '#{@apiKeyResolver}'
#            # 每秒最大访问次数
#            redis-rate-limiter.replenishRate: 2
#            # 令牌桶最大容量
#            redis-rate-limiter.burstCapacity: 2
  profiles:
    active: prod
server:
  port: 8080
  compression:
    enabled: true
    mime-types:
      - application/x-gzip
      - text/html
      - application/json
    min-response-size: 100
  connection-timeout: 10s
eureka:
  client:
    registry-fetch-interval-seconds: 30
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
  threadpool:
    default:
      coreSize: 3000
  shareSecurityContext: true
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE
    org.springframework.web.reactive: TRACE
    reactor.ipc.netty: TRACE
    reactor.netty: TRACE